[package]
name = "jsonwebtoken"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Create and parse JWT."
homepage = "https://github.com/Keats/rust-jwt"
repository = "https://github.com/Keats/rust-jwt"
keywords = ["jwt", "web", "api", "token", "json"]

[dependencies]
rustc-serialize = "0.3"
clippy = {version = "0.0.22", optional = true}
rust-crypto = "0.2.34"

[features]
default = []
dev = ["clippy"]

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
